# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xorg-x11-proto-dri2proto

# >> macros
# << macros

Summary:    X.Org X11 Protocol dri2proto
Version:    2.8
Release:    1
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/dri2proto-%{version}.tar.bz2
Source100:  xorg-x11-proto-dri2proto.yaml
Provides:   dri2proto

%description
This extension defines a protocol to securely allow user applications to access
the video hardware without requiring data to be passed through the X server.



%prep
%setup -q -n dri2proto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
# >> files
%{_includedir}/X11/extensions/dri2proto.h
%{_includedir}/X11/extensions/dri2tokens.h
%{_datadir}/pkgconfig/dri2proto.pc
%doc %{_docdir}/dri2proto/dri2proto.txt
# << files
